desktop_repo_url: "https://github.com/brownkurts/ansible_pull_desktop.git"
desktop_repo_branch: "master"

desktop_install_vscode: true

desktop_git_user_name: "Kurt Brown"
desktop_git_user_email: "brownkurts@gmail.com"

desktop_username: "kurt"
desktop_user_groups:
  - sudo
  - adm
  - plugdev

desktop_manage_ansible_pull_cron: true
desktop_ansible_pull_user: "root"
desktop_ansible_pull_minute: "*/10"
desktop_ansible_pull_log: "/var/log/ansible-pull.log"

desktop_install_chrome: true
desktop_install_tailscale: true

desktop_manage_background: true
desktop_manage_settings: true

desktop_wallpaper_src: "files/Stargate.png"
desktop_wallpaper_dest: "/usr/share/backgrounds/ansible-wallpaper2.png"

desktop_packages:
  - ansible
  - curl
  - dconf-cli
  - git
  - htop
  - mc
  - nano
  - net-tools
  - nfs-common
  - python3-psutil
  - rsync
  - vim
  - wget

desktop_install_remmina: true
desktop_manage_remmina: true
desktop_remmina_install_type: "apt"
desktop_remmina_profile_dir: "/home/{{ desktop_username }}/.local/share/remmina"

desktop_favorite_apps:
  - google-chrome.desktop
  - org.remmina.Remmina.desktop
  - org.gnome.Nautilus.desktop
  - org.gnome.Terminal.desktop

desktop_remmina_connections:
  - name: "blue"
    group: "Windows"
    protocol: "RDP"
    server: "192.168.2.38"
    username: "kurt"
    resolution_mode: 1
    multimon: 0
    span: 0

  - name: "brown-dc1"
    group: "Windows"
    protocol: "RDP"
    server: "192.168.2.5"
    username: "kbrown"
    domain: "brown.local"
    resolution_mode: 1
    multimon: 0
    span: 0

  - name: "brown-rds1"
    group: "Windows"
    protocol: "RDP"
    server: "192.168.2.14"
    username: "kbrown"
    domain: "brown.local"
    resolution_mode: 1
    multimon: 0
    span: 0

  - name: "desktop"
    group: "Windows"
    protocol: "RDP"
    server: "192.168.2.9"
    username: "kurt"
    resolution_mode: 1
    multimon: 1
    span: 0
    viewmode: 4
    window_maximize: 1

  - name: "work-vm"
    group: "Windows"
    protocol: "RDP"
    server: "192.168.2.108"
    username: "kurt"
    resolution_mode: 1
    multimon: 1
    span: 0
    viewmode: 4
    window_maximize: 1
    
  - name: "proxmox-01"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.2.201"
    username: "root"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "pve-noc"
    group: "Linux"
    protocol: "SSH"
    server: "74.91.16.2"
    username: "root"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "ks3-1"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.51"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "ks3-2"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.52"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "ks3-3"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.53"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "docker-01"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.11"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "docker-02"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.12"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "docker-03"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.13"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "destiny"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.201.10"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "kasm"
    group: "Linux"
    protocol: "SSH"
    server: "10.3.1.15"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "pihole1"
    group: "Linux"
    protocol: "SSH"
    server: "192.168.2.3"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"

  - name: "unifi"
    group: "Linux"
    protocol: "SSH"
    server: "74.91.16.5"
    username: "kurt"
    ssh_privatekey: "/home/kurt/.ssh/id_ed25519"