- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/cron.yml
    - include: tasks/packages.yml
   # - include: task/chrome.yml
   # - include: task/background.yml

    - name: copy wallpaper file
      copy:
        src: files/files/Stargate.png
        dest: /usr/share/backgrounds/Stargate.png
        owner: root
        group: root
 
    - name: set wallpaper
      become_user: kurt
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"
 
    - name: set wallpaper position
      become_user: kurt
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"