- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/packages.yml
    - include: tasks/chrome.yml
    - include: tasks/background.yml
    - include: tasks/settings.yml
    #- include: tasks/nfs.yml

  - name: send completion alert
    include_tasks: playbooks/send_completion_alert.yml
    tags: always
    when:
      - task_failed is not defined

  - name: send failure alert
    include_tasks: playbooks/send_failure_alert.yml
    tags: always
    when:
      - task_failed is defined
      - task_failed == true