---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update repositories
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - block:
        - name: Include user tasks
          include_tasks: tasks/users.yml

        - name: Include cron tasks
          include_tasks: tasks/cron.yml

        - name: Include package tasks
          include_tasks: tasks/packages.yml

        - name: Include Chrome tasks
          include_tasks: tasks/chrome.yml

        - name: Include background tasks
          include_tasks: tasks/background.yml

        - name: Include settings tasks
          include_tasks: tasks/settings.yml

        # - name: Include NFS tasks
        #   include_tasks: tasks/nfs.yml

        - name: Cleanup package cache (Debian and Ubuntu)
          apt:
            autoclean: yes
          changed_when: false
          when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

        - name: Autoremove orphan packages (Debian and Ubuntu)
          apt:
            autoremove: yes
            purge: yes
          when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]

  roles:
    - Linuxrmm
