- name: copy wallpaper file
  copy:
    src: files/daedalus.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: ansible
    group: root

- name: set wallpaper
  become_user: ansible
  shell: "dconf write /org/gnome/desktop/background/picture-uri '\"file:///usr/share/backgrounds/ansible-wallpaper.png\"'"
