- name: copy wallpaper file
  copy:
    src: files/daedalus.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: set wallpaper
  become_user: kurt
  shell: "dbus-launch dconf write /org/gnome/desktop/background/picture-uri '\"file:///usr/share/backgrounds/ansible-wallpaper.png\"'"
