- name: copy wallpaper file
  copy:
    src: files/Stargate.png
    dest: /usr/share/backgrounds/ansible-wallpaper2.png
    owner: root
    group: root
    mode: 0644

- name: set wallpaper
  become_user: kurt
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper2.png'"
