- name: copy wallpaper file
   copy:
    src: files/files/Stargate.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root
 
 - name: set wallpaper
    become_user: kurt
      dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"
 
- name: set wallpaper position
    become_user: kurt
      dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"