- name: copy wallpaper file
  copy:
    src: files/daedalus.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root

- name: set wallpaper
  become_user: kurt
  shell: "gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string --set /desktop/gnome/background/picture_filename /usr/share/backgrounds/ansible-wallpaper.png"
