- name: Copy wallpaper file
  copy:
    src: files/Stargate.png
    dest: /usr/share/backgrounds/ansible-wallpaper2.png
    owner: root
    group: root
    mode: 0644

- name: Set wallpaper for light mode
  become: true
  become_user: kurt
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "file:///usr/share/backgrounds/ansible-wallpaper2.png"

- name: Set wallpaper for dark mode
  become: true
  become_user: kurt
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "file:///usr/share/backgrounds/ansible-wallpaper2.png"
