    - name: copy wallpaper file
      copy:
        src: files/Stargate.png
        dest: /usr/share/backgrounds/Stargate.png
        owner: root
        group: root
 
    - name: set wallpaper
      become_user: kurt
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/Stargate.png'"
 
   # - name: set wallpaper position
    #  become_user: kurt
     # dconf:
      #  key: "/org/gnome/desktop/background/picture-options"
       # value: "zoom"