---
- name: Check if Google Chrome is installed
  ansible.builtin.stat:
    path: /usr/bin/google-chrome
  register: chrome_binary

- name: Download Google Chrome package
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: "0644"
  when:
    - ansible_os_family == "Debian"
    - not chrome_binary.stat.exists

- name: Install Google Chrome
  ansible.builtin.apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  when:
    - ansible_os_family == "Debian"
    - not chrome_binary.stat.exists

- name: Remove downloaded Chrome package
  ansible.builtin.file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent
  when: ansible_os_family == "Debian"