---
- name: Mount NFS Shares
  hosts: all
  become: true
  vars:
    nfsmounts:
      - path: /mnt/Public
        src: 192.168.2.22:/mnt/Public
      - path: /mnt/unraid
        src: 192.168.2.21:/mnt/user/unraid
      - path: /mnt/media
        src: 192.168.2.21:/mnt/user/Media
  tasks:
    - name: Create mount directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ nfsmounts }}"

    - name: Mount and persist NFS shares
      ansible.builtin.mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: nfs
        opts: defaults
        state: mounted
        dump: 0
        passno: 0
      loop: "{{ nfsmounts }}"

