---
- name: Check whether Tailscale is installed
  ansible.builtin.command: tailscale version
  register: tailscale_version
  failed_when: false
  changed_when: false

- name: Install Tailscale
  ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/bin/tailscale
  when:
    - ansible_os_family == "Debian"
    - tailscale_version.rc != 0