---
- name: Check if LinuxRMM agent is installed
  stat:
    path: "{{ rmm_installed_check }}"
  register: rmm_agent

- name: Ensure installation directory exists
  file:
    path: "{{ linuxrmm_install_dir }}"
    state: directory
    mode: '0755'
  when: not rmm_agent.stat.exists

- name: Download LinuxRMM installation script
  get_url:
    url: "https://raw.githubusercontent.com/netvolt/LinuxRMM-Script/main/rmmagent-linux.sh"
    dest: "{{ linuxrmm_install_dir }}/rmmagent-linux.sh"
    mode: '0755'
  when: not rmm_agent.stat.exists

- name: Run installation script
  command:
    cmd: >
      {{ linuxrmm_install_dir }}/rmmagent-linux.sh install
      '{{ rmm_arch }}' '{{ mesh_url }}' '{{ api_url }}'
      '{{ param_4 }}' '{{ param_5 }}' '{{ auth_key }}' '{{ device_name }}'
  args:
    chdir: "{{ linuxrmm_install_dir }}"
  register: install_output
  when: not rmm_agent.stat.exists

