---
- name: Ensure packages for RemoteApps
  apt:
    name:
      - freerdp2-x11
      - desktop-file-utils
    state: present
    update_cache: yes

- name: Set default users when not provided
  set_fact:
    remoteapps_users_effective: "{{ remoteapps_users | default([ansible_user | default('ubuntu')]) }}"

- name: Per-user RemoteApps setup
  include_tasks: per_user.yml
  loop: "{{ remoteapps_users_effective }}"
  loop_control:
    loop_var: target_user

- name: Update desktop database (harmless if missing)
  command: update-desktop-database
  changed_when: false
  failed_when: false
