---
- name: Ensure per-user bin dir exists
  file:
    path: "/home/{{ target_user }}/.local/bin/remoteapps"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"

- name: Ensure per-user applications dir exists
  file:
    path: "/home/{{ target_user }}/.local/share/applications"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0755"

- name: Create wrapper scripts for each RemoteApp
  template:
    src: "remoteapp.sh.j2"
    dest: "/home/{{ target_user }}/.local/bin/remoteapps/{{ item.name | lower | regex_replace('[^a-z0-9]+','-') }}.sh"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0700"
  loop: "{{ remoteapps }}"

- name: Create .desktop launchers for each RemoteApp
  template:
    src: "remoteapp.desktop.j2"
    dest: "/home/{{ target_user }}/.local/share/applications/{{ item.name | lower | regex_replace('[^a-z0-9]+','-') }}.desktop"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0644"
  loop: "{{ remoteapps }}"

- name: Confirm launcher created
  stat:
    path: "/home/{{ target_user }}/.local/share/applications/{{ item.name | lower | regex_replace('[^a-z0-9]+','-') }}.desktop"
  register: launcher_stats
  loop: "{{ remoteapps }}"
  loop_control:
    label: "{{ item.name }}"

- name: Report launcher creation
  debug:
    msg: "Launcher for {{ item.item.name }} exists: {{ item.stat.exists }} (user={{ target_user }})"
  loop: "{{ launcher_stats.results }}"
  loop_control:
    label: "{{ item.item.name }}"
