- name: send completion notification via telegram
  tags: always
  telegram:
    token: "{{ telegram_token }}"
    chat_id: "{{ telegram_chat_id }}"
    msg_format: markdown
    msg: "✔️  Ansible provision finished on *{{ ansible_hostname }}*"
  changed_when: False